name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test
  
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@remla23"
      - run: npm install
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # - run: 
      #     tag_name=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
      #     npm version --1.0.30
      # - run: git push origin HEAD:main --tags
      # - run: npm ci
      - name: change version
        run: |
          # tag_name=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          # echo "module.exports = { version: '$tag_name' }" > version-util.js
          npm version --tags
      - run: 
          npm ci
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          # github.token
      # - name: Print tag name # print the tag version without the prefix 'refs/tags/ '
      #   run: echo ${{ steps.created.outputs.tag_name }}

